### ISSUE TITLE
Inform the user that subtitles are being uploaded

### ISSUE THREAD

**Issue by Maxoudela** [vankasteelj/opensubtitles-uploader#16]
As I said here : http://blog.opensubtitles.eu/opensubtitlesorg/web/opensubtitles-uploader#comment-131774

When the website is not reachable (or takes time to respond), uploading a subtitle can take some time. Thus, when you click on the "send" button, nothing happen. You have to wait in order to see the "retry" option or the "successful" message.

I suggest to modify the UI in order to inform the user that the subtitle is being transferred, and to block any interaction. I'll be happy to provide a PR in necessary (even if I'm not familiar with NodeJS).

**Comment by vankasteelj** [comment]
you could grey out the entire ui like when a notification appears, and set a loading animation (a bar, advancing dots or a spinner), just to say "something is going on, wait up". Because there is no indication in the code about what's going on, the only control we have is "ok i sent a request" and "i got a response"

**Comment by Maxoudela** [comment]
I did notice that the little cloud next to the "send" button is blinking a bit.

Would you like me to try a PR for graying out and placing a little animation above the UI ? I have never touched NodeJs in my life but I can give it a try.

**Comment by vankasteelj** [comment]
it works as a website, really. It's just using node to take advantages of npm modules and some advanced functions
