### ISSUE TITLE
Something Went Wrong 

### ISSUE THREAD

**Issue by uckthis** [vankasteelj/opensubtitles-uploader#55]
Hello,
Since this Monday, whenever I try to upload a subtitle, it says "Something went wrong." It doesn't specify what went wrong and I don't know what to do. It's similar files that I have been uploading for about 6 months. When I upload them on website's uploader, subtitles upload. What is going on?

Thank you.

**Comment by vankasteelj** [comment]
use CTRL+D, go to the "console" tab and report the log here please

**Comment by vankasteelj** [comment]
%localappdata%\Opensubtitles-Uploader on Windows.

**Comment by vankasteelj** [comment]
You can also download https://dl.nwjs.io/v0.30.1/nwjs-sdk-v0.30.1-win-x64.zip and drop the content where Opensutitles-Uploader is located, and open the app with the nw.exe. You'll then have access to the developper tools.

**Comment by uckthis** [comment]
Here is the log:
http://pasted.co/74427302

**Comment by vankasteelj** [comment]
Thanks. From that log, the issue is on opensubtitles' part. Their server or their API is sending back an error. I've had similar issues with subtitles downloading through the API these past weeks, maybe it's related. You should go to them though, I sadly cannot help you as this is not an issue with my software directly

**Comment by vankasteelj** [comment]
Is it better now?

**Comment by uckthis** [comment]
@vankasteelj Yes, they've fixed it.
Thank you.
