### ISSUE TITLE
Build 2.4.0 doesn't start

### ISSUE THREAD

**Issue by tbertels** [vankasteelj/opensubtitles-uploader#57]
Build 2.4.0 doesn't start and is shown by Travis CI as failing https://travis-ci.org/vankasteelj/opensubtitles-uploader
Because of packages.json, opensubtitles-uploader prompts users to update to this non working version.

**Comment by vankasteelj** [comment]
![opensubtitles-uploader_2019-04-30_17-07-42](https://user-images.githubusercontent.com/12599850/56971973-7b3fe080-6b6a-11e9-8c76-da46475fa366.png)
Working fine for me

**Comment by tbertels** [comment]
I get this on Windows 7 (removing the user profile doesn't change anything, same with the portable version):

![osu](https://user-images.githubusercontent.com/3265870/56977162-dc6cb180-6b74-11e9-8f3a-4f50eb49fbde.png)

**Comment by tbertels** [comment]
However, it works in Windows XP compatibility mode.

**Comment by vankasteelj** [comment]
This seems like an OS issue. Maybe you should check your Windows installation and/or see with NWjs team if they encounter the same problem sometimes. 

As Windows 7 will stop recieving support in 2020, I won't spend some time virtualizing it to check if the issue is with my software, your win7 installation or nwjs itself. Sorry.

I will however add your compatibility fix in the readme in case other people encounter the same issue as you

**Comment by vankasteelj** [comment]
Q&A added to readme
